train:
  experiment_id: e1
  max_epochs: 200
  use_adam: true
  batch_size: 3
  max_nr_pts: 30000
  workers: 0
  optimizer:
    enable: true
    start_lr: 1e-06
    max_lr: 0.0001
    end_lr: 1e-05
    pct_incr_cycle: 0.1
    anneal_strategy: cos
    momentum: 0.9
  nr_submaps: 0
  load_pretrained: false
  sampling_method: random
  map_prob_rate: -1
  loss_weights:
    transf2map: 1.0
    map2transf: 1.0
    upsampling_reg: 0.2
  validation:
    nr_samples: 10000
    report_rate: 1
    save_result_rate: 500
grid:
  pose_distance: 15
  size:
  - 40.0
  - 40.0
  - 15.0
  dz: 4.0
  voxel_size: 0.1
  max_range: 20.0
  min_range: 2.0
  features:
  - intensity
  - label
  - eigenvalues
  - normals
  feature_dim:
  - 1
  - 1
  - 3
  - 3
  normal_eigenvalue_radius: 0.5
evaluation:
  float16: True
  target_map: map
  iou_grid:
    resolution:
    - 0.2
    - 0.2
    - 0.1
  f_score_dist: 0.1
  out_dir: experiments/results/kitti/
network:
  encoder_blocks:
  - type: GridSampleConv
    number_blocks: 3
    parameters:
      in_fdim:
      - 1
      - 16
      - 32
      out_fdim:
      - 16
      - 32
      - 32
      num_kernel_points: 27
      max_nr_neighbors:
      - 70
      - 50
      - 25
      relu: true
      batchnorm: true
      deformable: false
      subsampling_dist: 2
      map_size: 40
      subsampling_factor:
      - 0.1
      - 0.5
      - 1.0
      kernel_radius: 1.0
      min_kernel_radius: 1.5
      use_dif_sampling: false
  - type: LinearLayer
    number_blocks: 1
    parameters:
      in_fdim: 32
      out_fdim: 3
      relu: false
      batchnorm: false
  decoder_blocks:
  - type: AdaptiveDeconv
    number_blocks: 4
    parameters:
      number_blocks: 4
      block_id:
      - 0
      - 1
      - 2
      - 3
      subsampling_dist: 2
      in_fdim:
      - 3
      - 32
      - 32
      - 32
      out_fdim: 32
      kernel_radius: 0.05
      relu: true
      use_batch_norm: false
      inter_fdim: 128
      estimate_radius: false
      subsampling_fct_p1: 0.006
      subsampling_fct_p2: 1.764
  - type: LinearLayer
    number_blocks: 1
    parameters:
      in_fdim: 32
      out_fdim: 3
      relu: false
      batchnorm: false
  out_dir: network_files/
dataset:
  data_folders:
    grid_output: /data/
    prefix: /path/to/kitti/
    train:
    - '00'
    - '01'
    - '02'
    - '03'
    - '04'
    - '05'
    - '06'
    - '07'
    - '09'
    - '10'
    valid:
    - validation
    test:
    - '08'
git_commit_version: b'42d0bec'
